# Generated by hand for TanPit rest tickets

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pits", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="RestTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("hours", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=64)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rest_tickets",
                        to="pits.pit",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="restticket",
            constraint=models.CheckConstraint(
                condition=models.Q(hours__gt=0), name="restticket_hours_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="restticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(withdrawn_at__isnull=True),
                fields=("pit",),
                name="uniq_active_rest_ticket_per_pit",
            ),
        ),
    ]
